defaults: &defaults
  timeZone: { name: China, offset: 28800 }
  # mailer://smtp.exmail.qq.com:587/?user=报警<alarm@{{ .Domain }}>&pass=123456
  mailer: "mailer://smtp.qq.com:25/?user=小美<xiaomei-go@qq.com>&pass=zjsbosjlhgugechh"
  keepers: [ "小美<xiaomei-go@qq.com>" ]

name: {{ .ProName }}
envs:
  dev:
    <<: *defaults
    domain: {{ .ProNameUrlSafe }}.api.dev.{{ .Domain }}
    cookie:
      name: token-dev
      domain: api.dev.{{ .Domain }}
      path: /
      maxAge: 1M # y:年; M:月; d:天; h:时; m:分; s:秒
    secret: {{ genSecret }}
    keepers: [ ]
  test:
    <<: *defaults
    domain: localhost:3000
    secret: {{ genSecret }}
    keepers: [ ]
  ci:
    <<: *defaults
    domain: localhost:3000
    secret: {{ genSecret }}
  qa:
    <<: *defaults
    https: true
    domain: {{ .ProNameUrlSafe }}.api.qa.{{ .Domain }}
    cookie:
      name: token-dev
      domain: api.qa.{{ .Domain }}
      path: /
      maxAge: 1M # y:年; M:月; d:天; h:时; m:分; s:秒
    secret: {{ genSecret }}
  preview:
    <<: *defaults
    https: true
    domain: {{ .ProNameUrlSafe }}.api.preview.{{ .Domain }}
    cookie:
      name: token-dev
      domain: api.preview.{{ .Domain }}
      path: /
      maxAge: 1M # y:年; M:月; d:天; h:时; m:分; s:秒
    secret: {{ genSecret }}
  production:
    <<: *defaults
    https: true
    domain: {{ .ProNameUrlSafe }}.api.{{ .Domain }}
    cookie:
      name: token-dev
      domain: api.{{ .Domain }}
      path: /
      maxAge: 1M # y:年; M:月; d:天; h:时; m:分; s:秒
    secret: {{ genSecret }}

