language: go
go:
  - "1.10"
  - "1.11"
  - "1.12"
install:
  - go get -t ./...
script:
  - |
    if [[ $(go version) == *1.12* ]]; then
      go test -v -covermode=count -coverprofile=coverage.out ./...
      go get github.com/mattn/goveralls
      $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
    else
      go test -v ./...
    fi
notifications:
  email:
    applejava@qq.com
